---
- name: 3. Configure Control Plane
  hosts: control_plane
  become: true
  tasks:
    - name: Initialize the cluster on the first control plane node
      ansible.builtin.command: >
        kubeadm init --pod-network-cidr={{ pod_network_cidr }} --control-plane-endpoint={{ apiserver_endpoint }} --upload-certs
      args:
        creates: /etc/kubernetes/admin.conf
      when: inventory_hostname == groups['control_plane'][0]
      register: kubeadm_init

    - name: Store join commands
      ansible.builtin.set_fact:
        control_plane_join_command: "{{ kubeadm_init.stdout | regex_search('kubeadm join.*--control-plane.*') }}"
        worker_join_command: "{{ kubeadm_init.stdout | regex_search('kubeadm join.*--token.*') }}"
      when: inventory_hostname == groups['control_plane'][0]

    - name: Create .kube directory for root user
      ansible.builtin.file:
        path: /root/.kube
        state: directory
        mode: '0755'
      when: inventory_hostname == groups['control_plane'][0]

    - name: Copy admin.conf to user's kube config
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: true
        owner: root
        group: root
        mode: '0644'
      when: inventory_hostname == groups['control_plane'][0]

    - name: Install Calico CNI
      ansible.builtin.command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/calico.yaml
      args:
        creates: /etc/cni/net.d/10-calico.conflist
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      when: inventory_hostname == groups['control_plane'][0]

    - name: Join other control plane nodes
      ansible.builtin.command: "{{ hostvars[groups['control_plane'][0]]['control_plane_join_command'] }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
      when: inventory_hostname != groups['control_plane'][0]
