---
- name: 5. Validate Cluster
  hosts: control_plane[0]
  become: true
  tasks:
    - name: Wait for all nodes to be ready
      ansible.builtin.shell: |
        kubectl get nodes --no-headers | grep -v Ready | wc -l
      register: not_ready_nodes
      until: not_ready_nodes.stdout == "0"
      retries: 30
      delay: 10
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Get cluster status
      ansible.builtin.command: kubectl get nodes -o wide
      register: cluster_status
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Display cluster status
      ansible.builtin.debug:
        msg: "{{ cluster_status.stdout_lines }}"

    - name: Get pod status in kube-system
      ansible.builtin.command: kubectl get pods -n kube-system
      register: pod_status
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Display pod status
      ansible.builtin.debug:
        msg: "{{ pod_status.stdout_lines }}"
