kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: block-wait-keep
provisioner: pd.csi.storage.gke.io
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

